"""Update user model

Revision ID: dafee42b576b
Revises: 1bed9ef8155a
Create Date: 2025-05-21 01:34:24.164731+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafee42b576b'
down_revision = '1bed9ef8155a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('given_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('family_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'given_name')
    # ### end Alembic commands ###