"""Make ItineraryItemType subtypes all dicts and consolidate the table

Revision ID: e30033d6f5aa
Revises: df7900440457
Create Date: 2025-06-06 03:00:37.506207+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e30033d6f5aa'
down_revision = 'df7900440457'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary_items', sa.Column('details', sa.JSON(), nullable=True))
    op.drop_column('itinerary_items', 'raw_details_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary_items', sa.Column('raw_details_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('itinerary_items', 'details')
    # ### end Alembic commands ###