"""Make created_at and updated_at timestamptz

Revision ID: 1bed9ef8155a
Revises: 6f98acf2011c
Create Date: 2025-05-21 00:02:41.067065+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bed9ef8155a'
down_revision = '6f98acf2011c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###