"""Try to switch over table definitions

Revision ID: a89d32e095c0
Revises: dafee42b576b
Create Date: 2025-05-23 20:03:19.583760+00:00

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a89d32e095c0"
down_revision = "dafee42b576b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    participant_status_enum = postgresql.ENUM(
        "UNKNOWN",
        "INVITED",
        "JOINED",
        "DECLINED",
        "LEFT",
        name="participantstatus",
    )
    participant_status_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "itinerary_participants",
        "status",
        existing_type=postgresql.ENUM(
            "UNKNOWN",
            "INVITED",
            "JOINED",
            "DECLINED",
            "LEFT",
            name="itineraryparticipantstatus",
        ),
        type_=sa.Enum(
            "UNKNOWN", "INVITED", "JOINED", "DECLINED", "LEFT", name="participantstatus"
        ),
        existing_nullable=False,
        postgresql_using="status::text::participantstatus",
    )
    op.alter_column(
        "trip_participants",
        "status",
        existing_type=postgresql.ENUM(
            "UNKNOWN",
            "INVITED",
            "JOINED",
            "DECLINED",
            "LEFT",
            name="tripparticipantstatus",
        ),
        type_=sa.Enum(
            "UNKNOWN", "INVITED", "JOINED", "DECLINED", "LEFT", name="participantstatus"
        ),
        existing_nullable=False,
        postgresql_using="status::text::participantstatus",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trip_participants",
        "status",
        existing_type=sa.Enum(
            "UNKNOWN", "INVITED", "JOINED", "DECLINED", "LEFT", name="participantstatus"
        ),
        type_=postgresql.ENUM(
            "UNKNOWN",
            "INVITED",
            "JOINED",
            "DECLINED",
            "LEFT",
            name="tripparticipantstatus",
        ),
        postgresql_using="status::text::tripparticipantstatus",
        existing_nullable=False,
    )
    op.alter_column(
        "itinerary_participants",
        "status",
        existing_type=sa.Enum(
            "UNKNOWN", "INVITED", "JOINED", "DECLINED", "LEFT", name="participantstatus"
        ),
        type_=postgresql.ENUM(
            "UNKNOWN",
            "INVITED",
            "JOINED",
            "DECLINED",
            "LEFT",
            name="itineraryparticipantstatus",
        ),
        postgresql_using="status::text::itineraryparticipantstatus",
        existing_nullable=False,
    )

    # Drop the shared ENUM type
    participant_status_enum = postgresql.ENUM(
        "UNKNOWN",
        "INVITED",
        "JOINED",
        "DECLINED",
        "LEFT",
        name="participantstatus",
    )
    participant_status_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
